name: FTP Upload

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ${{ secrets.SERVER }}
          ftp-username: ${{ secrets.USERNAME }}
          ftp-password: ${{ secrets.PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
